# Encoding: UTF-8
# File: coco.py
# Creation: Tuesday December 29th 2020
# Author: arthurdjn
# ------
# Copyright (c) 2020, Makina Corpus


# Basic imports
from geolabel_maker.annotations.functional import extract_categories
from pathlib import Path
from datetime import datetime
from PIL import Image
import numpy as np


class COCO:
    r"""Defines an annotation for `Common Object in Context <http://cocodataset.org/>`__. 
    It follows the format used by Microsoft for ``COCO`` annotation.

    * :attr:`info` (dict, optional): Description of the annotation (metadata).

    * :attr:`images` (list): List of dictionaries containing metadata for the images in context.

    * :attr:`categories` (list): List of dictionaries containing the description of the categories used.

    * :attr:`annotations` (list): List of dictionaries containing the segmentation of an object associated to an image.

    """

    def __init__(self, images, categories, annotations, info=None):
        super().__init__()
        self.images = images
        self.categories = categories
        self.annotations = annotations
        self.info = info or {
            "description": "Auto-generated by Geolabel-Maker",
            "date_created": datetime.now().strftime("%Y/%m/%d")
        }

    @classmethod
    def build(cls, dir_images, dir_labels, categories, 
              pattern="*.*", root=None, is_crowd=False):
        r"""Generate a ``COCO`` annotation from a ``Dataset``.

        .. seealso::
            The provided dataset must contains a set of georeferenced images and categories (vectorized geometries).
            See ``Dataset`` for further details.

        Args:
            dataset (Dataset): The dataset containing the images and categories.
            zoom (int, optional): Zoom level used to generate the annotations.
            is_crowd (bool, optional): Defaults to ``False``.

        Returns:
            COCO
        """
        # Map the categories and their ids
        category2id = {category.name: i for i, category in enumerate(categories)}
        
        def get_annotations():
            # Retrieve the annotations (i.e. geometry / categories)
            coco_annotations = []
            annotation_id = 0
            for image_id, image_path in enumerate(dir_labels.rglob(pattern)):
                for category in extract_categories(image_path, categories):
                    category_id = category2id[category.name]
                    for _, row in category.data.iterrows():
                        polygon = row.geometry
                        # Get annotation elements
                        segmentation = np.array(polygon.exterior.coords).ravel().tolist()
                        x, y, max_x, max_y = polygon.bounds
                        width = max_x - x
                        height = max_y - y
                        bbox = (x, y, width, height)
                        area = polygon.area
                        # Make annotation format
                        coco_annotations.append({
                            "segmentation": [segmentation],
                            "iscrowd": int(is_crowd),
                            "image_id": image_id,
                            "image_name": image_path,
                            "category_id": category_id,
                            "id": annotation_id,
                            "bbox": bbox,
                            "area": area,
                        })
                        annotation_id += 1
            return coco_annotations

        def get_categories():
            # Create an empty categories' dictionary
            coco_categories = []
            for category in categories:
                category_id = category2id[category.name]
                coco_categories.append({
                    "id": category_id,
                    "name": category.name,
                    "supercategory": category.name
                })
            return coco_categories

        def get_images():
            # Retrieve image paths / metadata
            coco_images = []
            for image_id, image_path in enumerate(dir_images.rglob(pattern)):
                # get image info
                img = Image.open(image_path)
                width, height = img.size
                filename = str(image_path)
                # create image description
                coco_images.append({
                    "id": image_id,
                    "width": width,
                    "height": height,
                    "file_name": filename
                })
            return coco_images

        def get_info():
            return {
                "description": "Auto-generated by Geolabel-Maker",
                "date_created": datetime.now().strftime("%Y/%m/%d"),
            }

        # Create the annotation as a dict
        info = get_info()
        images = get_images()
        categories = get_categories()
        annotations = get_annotations()

        return COCO(images, categories, annotations, info)

    def to_dict(self):
        return {
            "info": self.info,
            "images": self.images,
            "categories": self.categories,
            "annotations": self.annotations
        }

    def __repr__(self):
        return f"COCO(images={len(self.images)}, categories={len(self.categories)}, annotations={len(self.annotations)})"
